//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblCustomerShippings = new HashSet<tblCustomerShipping>();
            this.tblOffers = new HashSet<tblOffer>();
            this.tblOrders = new HashSet<tblOrder>();
            this.tblProductHistories = new HashSet<tblProductHistory>();
            this.tblPurchasOrderDetails = new HashSet<tblPurchasOrderDetail>();
        }
    
        public System.Guid CustomerId { get; set; }
        public string Name { get; set; }
        public string OrganizationName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostOffice { get; set; }
        public string Kommune { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string BankAccount { get; set; }
        public string IBAN { get; set; }
        public string SwiftCode { get; set; }
        public string ContactNoConfirmOrder { get; set; }
        public string OrganizationNumber { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public bool IsVISMA { get; set; }
        public string City { get; set; }
        public bool IsUser { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CustomerNo { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblCurrency tblCurrency { get; set; }
        public virtual tblFile tblFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerShipping> tblCustomerShippings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOffer> tblOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductHistory> tblProductHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchasOrderDetail> tblPurchasOrderDetails { get; set; }
    }
}
