//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOfferDetail
    {
        public System.Guid OfferDetailId { get; set; }
        public System.Guid OfferId { get; set; }
        public System.Guid ProductId { get; set; }
        public string ProductName { get; set; }
        public string History { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> ProductStock { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<int> OfferQty { get; set; }
        public string OfferRemarks { get; set; }
        public System.Guid StatusId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> CustomerPrice { get; set; }
        public Nullable<int> CustomerQty { get; set; }
        public string CustomerRemarks { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<int> FinalQty { get; set; }
        public string FinalRemarks { get; set; }
        public string ProductUCPCode { get; set; }
    
        public virtual tblOffer tblOffer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
