//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOffer()
        {
            this.tblOfferDetails = new HashSet<tblOfferDetail>();
        }
    
        public System.Guid OfferId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid StatusId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsVISMA { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> OfferAcceptanceDate { get; set; }
        public Nullable<System.DateTime> OfferApprovalDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferDetail> tblOfferDetails { get; set; }
    }
}
