//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductHistory
    {
        public System.Guid ProductHistoryId { get; set; }
        public System.Guid CustomerId { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public System.DateTime SaleDate { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid StatusId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ProductName { get; set; }
        public string Remarks { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
