//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductFile
    {
        public System.Guid ProductFileId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid FileId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual tblFile tblFile { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
