//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vArticleCustomField
    {
        public string ArticleNo { get; set; }
        public Nullable<int> Factor { get; set; }
        public Nullable<int> FactorCalcMethod { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> ContributionCurrentPeriod { get; set; }
        public Nullable<int> ContributionYear { get; set; }
        public Nullable<int> ContributionPercent { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> AgreedPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public string PriceType { get; set; }
        public string FirstDate { get; set; }
        public string LastDate { get; set; }
        public Nullable<int> DiscountI { get; set; }
        public Nullable<int> DiscountII { get; set; }
        public Nullable<int> DiscountIII { get; set; }
        public Nullable<System.DateTime> Price1FromDate { get; set; }
        public Nullable<System.DateTime> SupplPriceFromDate { get; set; }
        public Nullable<System.DateTime> FullCostFromDate { get; set; }
        public Nullable<System.DateTime> PriceCalcDate { get; set; }
        public string InActiveStatus { get; set; }
        public Nullable<decimal> PriceTimesPurchUnit { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<int> UpdateStock { get; set; }
        public Nullable<System.DateTime> LastMovementDate { get; set; }
        public Nullable<int> AutoConsumptionYesNo { get; set; }
        public Nullable<int> WeightedPurchasePriceYesNo { get; set; }
        public Nullable<decimal> ExchangePrice { get; set; }
        public string CurrencyNo { get; set; }
        public string TemplateArticle { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ComparableUnitPrice { get; set; }
        public string ComparableUnitType { get; set; }
        public Nullable<int> ContributionInCurrency { get; set; }
        public Nullable<int> ColorMark { get; set; }
        public bool IsUpdated { get; set; }
    }
}
