//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vArticle
    {
        public string ArticleNo { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<int> PriceCalcMethodsNo { get; set; }
        public Nullable<int> QuantityPerUnitPurchase { get; set; }
        public Nullable<int> QuantityPerUnitSale { get; set; }
        public Nullable<int> StockProfileNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> StopDateOfferPrice { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> WarehouseNo { get; set; }
        public Nullable<int> PostingTemplateNo { get; set; }
        public Nullable<decimal> AgreedPrice { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> DiscountI { get; set; }
        public Nullable<decimal> DiscountII { get; set; }
        public Nullable<int> MainGroupNo { get; set; }
        public Nullable<int> IntermediateGroupNo { get; set; }
        public Nullable<int> SubGroupNo { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<bool> InActiveYesNo { get; set; }
        public Nullable<int> WebshopLastAvailableInStock { get; set; }
        public Nullable<bool> WebshopArticleYesNo { get; set; }
        public Nullable<bool> ShowOnWebYesNo { get; set; }
        public Nullable<bool> MainStructureArtYesNo { get; set; }
        public Nullable<bool> CountedYesNo { get; set; }
        public string PicturePath { get; set; }
        public string MemoFilePath { get; set; }
        public string POSArticleInfo { get; set; }
        public Nullable<int> EUFiguresNo { get; set; }
        public Nullable<int> CountryOfOriginNo { get; set; }
        public bool IsUpdated { get; set; }
    }
}
