//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCustomer
    {
        public int CustomerNo { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string EmailAddress { get; set; }
        public string Address2 { get; set; }
        public string PostCode { get; set; }
        public string PostOffice { get; set; }
        public Nullable<int> CountryNo { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> InActiveYesNo { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> FormProfileCustNo { get; set; }
        public Nullable<int> DeliveryMethodsNo { get; set; }
        public Nullable<int> BusinessNo { get; set; }
        public Nullable<int> CustomerProfileNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> TermsOfPayCustNo { get; set; }
        public Nullable<int> CustomerGrpNo { get; set; }
        public Nullable<int> DistrictNo { get; set; }
        public Nullable<int> PriceCode { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CompanyNo { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> OurSupplNo { get; set; }
        public Nullable<int> CustomerTypeNo { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string Password { get; set; }
        public Nullable<int> ChainLeaderYesNo { get; set; }
        public Nullable<int> TypeOfChain { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> DepNo { get; set; }
        public Nullable<int> SupplierNo { get; set; }
        public Nullable<int> DeliveryAddressNo { get; set; }
        public string Address3 { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> ExtraCostUnitIVNo { get; set; }
        public Nullable<int> ExtraCostUnitIIINo { get; set; }
        public Nullable<int> ExtraCostUnitIINo { get; set; }
        public Nullable<int> ExtraCostUnitINo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string EANLocationNo { get; set; }
        public Nullable<int> CustomerBonusProfileNo { get; set; }
        public Nullable<int> LocalGovernmentNo { get; set; }
        public Nullable<int> ChartererCompanyNo { get; set; }
        public Nullable<int> AgentNo { get; set; }
        public Nullable<int> CommissionProfileNo { get; set; }
        public Nullable<int> RemittanceProfileNo { get; set; }
        public string AutogiroAgreementID { get; set; }
        public Nullable<int> AgentYesNo { get; set; }
        public Nullable<int> ShipmentTypeNo { get; set; }
        public Nullable<int> RemainderOrderYesNo { get; set; }
        public Nullable<int> AcceptReplacementArticleYesNo { get; set; }
        public Nullable<int> PrintProfileNo { get; set; }
        public Nullable<int> PaymentPattern { get; set; }
        public Nullable<int> AltPriceListYesNo { get; set; }
        public Nullable<int> AltPriceListNo { get; set; }
        public Nullable<int> InvoiceAdressNo { get; set; }
        public Nullable<int> EdiProfileNo { get; set; }
        public Nullable<int> EinvoiceStatus { get; set; }
        public string EinvoiceRef { get; set; }
        public string EDISellerRefNo { get; set; }
        public string EDIBuyerRefNo { get; set; }
        public string VATRegNo { get; set; }
        public string WebshopRefNo { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> SwiftCodeNo { get; set; }
        public Nullable<int> ContactNoConfirmOrder { get; set; }
        public Nullable<int> ContactNoPickingList { get; set; }
        public bool IsUpdated { get; set; }
    }
}
