//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSupplier
    {
        public int SupplierNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public string PostCode { get; set; }
        public string PostOffice { get; set; }
        public string Telephone { get; set; }
        public string Telefax { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> FormProfileSuppNo { get; set; }
        public Nullable<int> DeliveryMethodsNo { get; set; }
        public Nullable<int> TermsOfDeliveryNo { get; set; }
        public Nullable<int> SwiftCodeNo { get; set; }
        public string PostAccount { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> CountryNo { get; set; }
        public string Address1 { get; set; }
        public string SortName { get; set; }
        public Nullable<int> BuContactNo { get; set; }
        public Nullable<int> SupplierGrpNo { get; set; }
        public Nullable<int> BusinessNo { get; set; }
        public Nullable<int> SupplierProfileNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> TermsOfPaySupplNo { get; set; }
        public Nullable<int> WareHouseNo { get; set; }
        public string OurCustomerNo { get; set; }
        public string CompanyNo { get; set; }
        public Nullable<int> DistrictNo { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> GLAccPay { get; set; }
        public Nullable<int> SupplierTypeNo { get; set; }
        public Nullable<int> DiscountGrpSupplNo { get; set; }
        public Nullable<System.DateTime> LastMovementDate { get; set; }
        public Nullable<bool> InActiveYesNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string Password { get; set; }
        public Nullable<int> CustomerNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> DepNo { get; set; }
        public Nullable<int> SupplierClassification { get; set; }
        public Nullable<int> ChainNo { get; set; }
        public string WWWAddress { get; set; }
        public string Address3 { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> ExtraCostUnitIVNo { get; set; }
        public Nullable<int> ExtraCostUnitIIINo { get; set; }
        public Nullable<int> ExtraCostUnitIINo { get; set; }
        public Nullable<int> ExtraCostUnitINo { get; set; }
        public Nullable<int> RemittanceProfileNo { get; set; }
        public Nullable<int> LocalGovernmentNo { get; set; }
        public Nullable<int> ReminderProfileNo { get; set; }
        public Nullable<int> NoOfReceivedPrOrder { get; set; }
        public Nullable<int> AvgDaysDelayedDelivery { get; set; }
        public Nullable<int> EbusinessType { get; set; }
        public Nullable<int> OrderConfirmationTime { get; set; }
        public string EANLocationNo { get; set; }
        public string VATRegNo { get; set; }
        public Nullable<int> PrefGLAccountNo { get; set; }
        public Nullable<int> PLAttResponsible { get; set; }
        public string BankGiro { get; set; }
        public Nullable<int> RiksBankKod { get; set; }
        public string BankName { get; set; }
        public string PgKontorUtland { get; set; }
        public string Telephone2 { get; set; }
        public Nullable<int> LanguageNo { get; set; }
        public Nullable<int> BankConNo { get; set; }
        public Nullable<int> ForeignPaymentYesNo { get; set; }
        public Nullable<int> CurrencyAccount { get; set; }
        public string UserNumber { get; set; }
        public Nullable<int> KIDSupplier { get; set; }
        public string ForeignBankCode { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string GLAccPayAlfa { get; set; }
        public Nullable<int> AccountingRuleNo { get; set; }
        public Nullable<int> EuroFicka { get; set; }
        public Nullable<int> TransType { get; set; }
        public string TransTypeText { get; set; }
        public Nullable<int> AttestationResponsible { get; set; }
        public Nullable<int> FloatGroupNo { get; set; }
        public Nullable<int> ChartererCompanyNo { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> DateLastFinancialStatement { get; set; }
        public Nullable<int> AnnualSales { get; set; }
        public Nullable<int> NoOfEmployees { get; set; }
        public Nullable<int> CostTrackingProfileNo { get; set; }
        public bool IsUpdated { get; set; }
    }
}
