using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Scheduler.Model
{
    class Supplier
    {
        public const string ARRAY_SUPPLIERS = "Suppliers";
        public const string SupplierNo = "SupplierNo";
        public const string Name = "Name";
        public const string ContactNo = "ContactNo";
        public const string PostCode = "PostCode";
        public const string PostOffice = "PostOffice";
        public const string Telephone = "Telephone";
        public const string Telefax = "Telefax";
        public const string EmailAddress = "EmailAddress";
        public const string FormProfileSuppNo = "FormProfileSuppNo";
        public const string DeliveryMethodsNo = "DeliveryMethodsNo";
        public const string TermsOfDeliveryNo = "TermsOfDeliveryNo";
        public const string SwiftCodeNo = "SwiftCodeNo";
        public const string PostAccount = "PostAccount";
        public const string BankAccount = "BankAccount";
        public const string CountryNo = "CountryNo";
        public const string Address1 = "Address1";
        public const string SortName = "SortName";
        public const string BuContactNo = "BuContactNo";
        public const string SupplierGrpNo = "SupplierGrpNo";
        public const string BusinessNo = "BusinessNo";
        public const string SupplierProfileNo = "SupplierProfileNo";
        public const string EmployeeNo = "EmployeeNo";
        public const string TermsOfPaySupplNo = "TermsOfPaySupplNo";
        public const string WareHouseNo = "WareHouseNo";
        public const string OurCustomerNo = "OurCustomerNo";
        public const string CompanyNo = "CompanyNo";
        public const string DistrictNo = "DistrictNo";
        public const string CurrencyNo = "CurrencyNo";
        public const string CreditLimit = "CreditLimit";
        public const string GLAccPay = "GLAccPay";
        public const string SupplierTypeNo = "SupplierTypeNo";
        public const string DiscountGrpSupplNo = "DiscountGrpSupplNo";
        public const string LastMovementDate = "LastMovementDate";
        public const string InActiveYesNo = "InActiveYesNo";
        public const string RegistrationDate = "RegistrationDate";
        public const string AccessLevel = "AccessLevel";
        public const string Password = "Password";
        public const string CustomerNo = "CustomerNo";
        public const string ProjectNo = "ProjectNo";
        public const string ProductNo = "ProductNo";
        public const string DepNo = "DepNo";
        public const string SupplierClassification = "SupplierClassification";
        public const string ChainNo = "ChainNo";
        public const string WWWAddress = "WWWAddress";
        public const string Address3 = "Address3";
        public const string Address2 = "Address2";
        public const string LastUpdate = "LastUpdate";
        public const string ExtraCostUnitIVNo = "ExtraCostUnitIVNo";
        public const string ExtraCostUnitIIINo = "ExtraCostUnitIIINo";
        public const string ExtraCostUnitIINo = "ExtraCostUnitIINo";
        public const string ExtraCostUnitINo = "ExtraCostUnitINo";
        public const string RemittanceProfileNo = "RemittanceProfileNo";
        public const string LocalGovernmentNo = "LocalGovernmentNo";
        public const string ReminderProfileNo = "ReminderProfileNo";
        public const string NoOfReceivedPrOrder = "NoOfReceivedPrOrder";
        public const string AvgDaysDelayedDelivery = "AvgDaysDelayedDelivery";
        public const string EbusinessType = "EbusinessType";
        public const string OrderConfirmationTime = "OrderConfirmationTime";
        public const string EANLocationNo = "EANLocationNo";
        public const string VATRegNo = "VATRegNo";
       // public const string PrefGLAccountNo = "PrefGLAccountNo";
        public const string PLAttResponsible = "PLAttResponsible";
        public const string BankGiro = "BankGiro";
        public const string RiksBankKod = "RiksBankKod";
        public const string BankName = "BankName";
        public const string PgKontorUtland = "PgKontorUtland";
        public const string Telephone2 = "Telephone2";
        public const string LanguageNo = "LanguageNo";
        public const string BankConNo = "BankConNo";
        //public const string ForeignPaymentYesNo = "ForeignPaymentYesNo";
        public const string CurrencyAccount = "CurrencyAccount";
        public const string UserNumber = "UserNumber";
        public const string KIDSupplier = "KIDSupplier";
        public const string ForeignBankCode = "ForeignBankCode";
        public const string CountryCode = "CountryCode";
        public const string PaymentMethod = "PaymentMethod";
        public const string GLAccPayAlfa = "GLAccPayAlfa";
        public const string AccountingRuleNo = "AccountingRuleNo";
        public const string EuroFicka = "EuroFicka";
        public const string TransType = "TransType";
        public const string TransTypeText = "TransTypeText";
        public const string AttestationResponsible = "AttestationResponsible";
        public const string FloatGroupNo = "FloatGroupNo";
        public const string ChartererCompanyNo = "ChartererCompanyNo";
        public const string IBAN = "IBAN";
        public const string DateLastFinancialStatement = "DateLastFinancialStatement";
        public const string AnnualSales = "AnnualSales";
        public const string NoOfEmployees = "NoOfEmployees";
        public const string CostTrackingProfileNo = "CostTrackingProfileNo";
    }
}
