//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerShipping
    {
        public System.Guid CustomerShippingId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostOffice { get; set; }
        public string Kommune { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsVISMA { get; set; }
        public int AddressId { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
