//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public System.Guid EmployeeId { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string InternalTelephone { get; set; }
        public string MobileTelephone { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string PostOffice { get; set; }
        public string PostCode { get; set; }
        public string Address1 { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.Guid> ReportsToId { get; set; }
        public string BankAccount { get; set; }
        public string PostAccount { get; set; }
        public string Email { get; set; }
        public string Address3 { get; set; }
        public string Address2 { get; set; }
        public string NickName { get; set; }
        public Nullable<int> Sex { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public System.Guid StatusId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public bool IsVISMA { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblFile tblFile { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
