//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductSupplierHistory
    {
        public System.Guid ProductSupplierHistoryId { get; set; }
        public System.Guid SupplierId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ProductName { get; set; }
        public string Remarks { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
