//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCustomerAddress
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string InvoiceAdress1 { get; set; }
        public string InvoiceAdress2 { get; set; }
        public string InvoiceAdress3 { get; set; }
        public string PostCode { get; set; }
        public string PostOffice { get; set; }
        public bool IsUpdated { get; set; }
        public int CustomerNo { get; set; }
    }
}
