//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCustomerCustomField
    {
        public System.Guid CustomField { get; set; }
        public Nullable<int> CustomerNo { get; set; }
        public Nullable<int> Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsUpdated { get; set; }
    }
}
