//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployee
    {
        public int EmployeeNo { get; set; }
        public string Name { get; set; }
        public string Titel { get; set; }
        public Nullable<int> DepNo { get; set; }
        public string InternalTelephone { get; set; }
        public string MobileTelephone { get; set; }
        public Nullable<int> CountryNo { get; set; }
        public string PostOffice { get; set; }
        public string PostCode { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> CommissionNo { get; set; }
        public string Telefax { get; set; }
        public string PrivateTelephone { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public string NameReportsTo { get; set; }
        public Nullable<bool> InActiveYesNo { get; set; }
        public string BankAccount { get; set; }
        public string PostAccount { get; set; }
        public string InternalEmailAddress { get; set; }
        public string PrivateEmailAddress { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public string Address3 { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string NickName { get; set; }
        public string BusyReason { get; set; }
        public Nullable<bool> BusyStatus { get; set; }
        public Nullable<System.DateTime> EndedDate { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Bleeper { get; set; }
        public string PersonalWWWAddress { get; set; }
        public Nullable<int> UserNo { get; set; }
        public string Birthday { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public string ParentFamilyName { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> EbusinessType { get; set; }
        public string Password { get; set; }
        public Nullable<int> PLUser { get; set; }
        public Nullable<int> TSApproverEmployeeNo { get; set; }
        public Nullable<bool> DeviationControlYesNo { get; set; }
        public Nullable<bool> SubstManagerYesNo { get; set; }
        public Nullable<int> EmployeeCatNo { get; set; }
        public Nullable<int> TimeCostPrice { get; set; }
        public Nullable<int> TimeSalesPrice { get; set; }
        public Nullable<int> WorkingHours { get; set; }
        public Nullable<bool> AllowTimeSheetRegAllUsers { get; set; }
        public Nullable<int> UseWagesortYesNo { get; set; }
        public Nullable<int> TimeWgSrtNo { get; set; }
        public Nullable<int> DeputyNo { get; set; }
        public Nullable<int> MaxAttestationAmount { get; set; }
        public Nullable<int> SuperiorNo { get; set; }
        public Nullable<int> WareHouseNo { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
