//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPO
    {
        public string SupplierOrderNo { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> SupplierOrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string OurRef { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public string NameContactNo { get; set; }
        public Nullable<int> SupplierNo { get; set; }
        public Nullable<int> TermsOfPaySupplNo { get; set; }
        public Nullable<int> WareHouseNo { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> DepNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> VATCode { get; set; }
        public Nullable<int> TaxClassNo { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> DeliveredYesNo { get; set; }
        public string Address1 { get; set; }
        public string PostOffice { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CountryNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> DeliveryMethodsNo { get; set; }
        public Nullable<int> TermsOfDeliveryNo { get; set; }
        public Nullable<int> TotalDelivery { get; set; }
        public Nullable<int> InvoiceFee { get; set; }
        public Nullable<int> HandlingCharge { get; set; }
        public Nullable<int> Postage { get; set; }
        public Nullable<int> PurchaseDiscount { get; set; }
        public Nullable<int> PurchaseDiscountTaxFree { get; set; }
        public Nullable<int> PostageTaxFree { get; set; }
        public Nullable<int> CashDiscount { get; set; }
        public Nullable<int> CashDiscountTaxFree { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ExchangeAmount { get; set; }
        public Nullable<int> ExchangeRate { get; set; }
        public string CompanyNo { get; set; }
        public Nullable<int> TotalVAT { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> DeliveryAddressNo { get; set; }
        public Nullable<int> DeliveryCountryNo { get; set; }
        public string DeliveryPostOffice { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryPostCode { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> OrderConfirmationDate { get; set; }
        public string SuppliersOrderNoRef { get; set; }
        public Nullable<int> TotalAmountFromInvoice { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> RemainderOrderYesNo { get; set; }
        public Nullable<int> FreightCost { get; set; }
        public Nullable<int> OrderType { get; set; }
        public bool IsUpdated { get; set; }
    }
}
