//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPOLine
    {
        public System.Guid POLineId { get; set; }
        public string AltArtNo { get; set; }
        public Nullable<int> Amount { get; set; }
        public string ArticleNo { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DepNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> DiscountGrpArtNo { get; set; }
        public Nullable<int> DiscountI { get; set; }
        public string EANNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> ExchangeAmount { get; set; }
        public Nullable<int> ExchangePurchasePrice { get; set; }
        public Nullable<int> ExchangeRate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> FullCost { get; set; }
        public Nullable<int> Invoiced { get; set; }
        public Nullable<int> InvoicePrice { get; set; }
        public string Name { get; set; }
        public Nullable<int> NetDeliveryAmount { get; set; }
        public Nullable<int> NetRemainderAmount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> OriginalLineNo { get; set; }
        public Nullable<int> OriginalPrice { get; set; }
        public Nullable<int> OriginalQuantity { get; set; }
        public Nullable<int> PartReceived { get; set; }
        public Nullable<int> PostingTemplateNo { get; set; }
        public Nullable<int> PriceCalculationNo { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Remainder { get; set; }
        public Nullable<int> StockProfileNo { get; set; }
        public Nullable<int> SupplierNo { get; set; }
        public string SupplierOrderNo { get; set; }
        public Nullable<int> TaxClassNo { get; set; }
        public Nullable<int> VATCode { get; set; }
        public Nullable<int> WareHouseNo { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> SuppliersOrderLineNo { get; set; }
        public Nullable<int> TotalInvoiced { get; set; }
        public Nullable<int> UniqueId { get; set; }
        public Nullable<int> UnitHeight { get; set; }
        public Nullable<int> UnitWidth { get; set; }
        public Nullable<int> UnitLength { get; set; }
        public Nullable<int> UnitTypeNo { get; set; }
        public bool IsUpdated { get; set; }
    }
}
