//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSO
    {
        public string OrderNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ContactNoInvoice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string OurRef { get; set; }
        public Nullable<int> CustomerGrpNo { get; set; }
        public Nullable<int> DepNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> VATCode { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public string InvoicePostOffice { get; set; }
        public string InvoiceAddress1 { get; set; }
        public string DeliveryPostOffice { get; set; }
        public string InvoicePostCode { get; set; }
        public Nullable<int> CustomerNo { get; set; }
        public Nullable<int> DeliveryCountryNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public string DeliveryAddress1 { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string CompanyNo { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> TotalVAT { get; set; }
        public string DeliveryPostCode { get; set; }
        public Nullable<int> ExchangeAmount { get; set; }
        public Nullable<int> ExchangeRate { get; set; }
        public Nullable<int> PurchaseNo { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> ContactNoDelivery { get; set; }
        public string InvoiceAddress2 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public Nullable<int> FactNo { get; set; }
        public Nullable<int> TotalWeightDelivered { get; set; }
        public string FactCustomerNo { get; set; }
        public string OriginalOrderNo { get; set; }
        public Nullable<int> AgreedAmount { get; set; }
        public Nullable<int> TermsOfDeliveryNo { get; set; }
        public Nullable<int> PaymentTypeNo { get; set; }
        public Nullable<int> TermsOfPayCustNo { get; set; }
        public Nullable<bool> CashPaymentYesNo { get; set; }
        public string InvoiceEmailAddress { get; set; }
        public string YourReference { get; set; }
        public Nullable<int> HandlingCharge { get; set; }
        public Nullable<int> Postage { get; set; }
        public Nullable<int> FreightcostPer { get; set; }
        public Nullable<int> DeliveryMethodsNo { get; set; }
        public Nullable<int> OrderType { get; set; }
        public bool IsUpdated { get; set; }
    }
}
