//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSOLine
    {
        public System.Guid SOLineId { get; set; }
        public string OrderNo { get; set; }
        public string AltArtNo { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> DepNo { get; set; }
        public string EANNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PLUNo { get; set; }
        public Nullable<int> PostingTemplateNo { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> TotalDelivered { get; set; }
        public Nullable<int> Amount { get; set; }
        public string ArticleNo { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DiscountI { get; set; }
        public Nullable<int> DiscountII { get; set; }
        public Nullable<int> DistributionFormulaNo { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> ExchangeAmount { get; set; }
        public Nullable<int> ExchangeRate { get; set; }
        public Nullable<int> ExchangeSalesPrice { get; set; }
        public Nullable<int> FullCost { get; set; }
        public Nullable<int> GLSalesAccountNo { get; set; }
        public Nullable<int> GrossPrice { get; set; }
        public Nullable<int> IntermediateGroupNo { get; set; }
        public Nullable<int> Invoiced { get; set; }
        public Nullable<int> MainGroupNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> NetDeliveryAmount { get; set; }
        public Nullable<int> NetPrice { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Remainder { get; set; }
        public Nullable<int> SubGroupNo { get; set; }
        public Nullable<int> TaxClassNo { get; set; }
        public Nullable<int> VATCode { get; set; }
        public Nullable<int> WareHouseNo { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> UniqueId { get; set; }
        public Nullable<int> PartDelivered { get; set; }
        public Nullable<int> UnitHeight { get; set; }
        public Nullable<int> UnitWidth { get; set; }
        public Nullable<int> UnitLength { get; set; }
        public Nullable<int> UnitTypeNo { get; set; }
        public bool IsUpdated { get; set; }
    }
}
